### ISSUE TITLE
About the training of the sampling location offsets 

### ISSUE THREAD

**Issue by sstzal** [yuexy/PS-ViT#6]
Hi, Xiaoyu
This PS-ViT is an excellent work! And I have a little question want to ask: When I train the sampling location offsets network, the output offsets are always very high (nearly the H/W of the image) or low (nearly 0). Have you ever encountered this kind of problem？ How do you limit the range of the learned offsets?
![image](https://user-images.githubusercontent.com/40749976/138986576-2ed95107-a775-4719-8d91-43ecbce44912.png)

Looking forward to your reply! Thanks!

**Comment by yuexy** [comment]
Hi sstzal,
Thank you for your kind interest in our work. We didn't limit the range of the learned offsets, but we initialized the learnable weight $M_t$ as 0 (https://github.com/yuexy/PS-ViT/blob/master/models/ps_vit.py#L126).
For more details, please refer to our code.
