### ISSUE TITLE
Can't load pretrained model

### ISSUE THREAD

**Issue by Lansieuva** [yuexy/PS-ViT#8]
Thansk for your great work. I tried to train PS-ViT on my own dataset based on your ImageNet pretrained model. But when I use create_model(initial_checkpoint) in your code to load ps_vit_b_18.pth.tar, something goes wrong. Can you help me solve this problem? Thansk again!
![{%4{XGSIU51N1GR{G0TIDAQ](https://user-images.githubusercontent.com/58927039/148665713-882f1c00-65d6-48ce-b8cf-e97bf5d13378.png)

**Comment by whiteBAI-97** [comment]
Hello, I'm also following up this project recently. Is it convenient to exchange contact information? My email 874906294@qq.com

**Comment by yuexy** [comment]
Hi, thanks for the report.
I just fixed the bug, pls fetch the lastest version and try again.
